### ISSUE TITLE
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [mjsull/HaploFlow#1]
I untarred on Linux (RHEL 7) and got this error:

```
% ./HapFlow
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "HapFlow.py", line 24, in <module>
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory, please install the python-tk package
```

Does it mean a particular python-tk package via pip?
Or system library?
I seem to have `/usr/lib64/libtk8.5.so` installed.

PS. It seems be linked fine against the local `HapFlow_1.1.2_linux/./libpython2.7.so.1.0`

**Comment by mjsull** [comment]
Hi Torsten,

Sorry for taking so long to get back to you, just moved half way across the world for a postdoc (Also thanks for the tweet).

I built HapFlow with cx_freeze on Ubuntu 15, I didn't realise it at the time but apparently the ABIs may be incompatible with versions of Linux with older libraries.

I'll create a live usb and rebuild later in the week, until then the python script should work (See: Running as a python application http://mjsull.github.io/HapFlow/files.html)

**Comment by tseemann** [comment]
No worries, whenever you get around to it. I'll get a notification here when you find time. All the best!
